server:
  port: 9000 # The gateway runs on port 9000

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: greeting_route # A unique name for the routes
          uri: lb://GREETING-SERVICE
          predicates:
            - Path=/greeting/**

# Configure it as a Eureka client so it can find other services
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/


  